# 默认配置文件
# 所有配置都在这里，尽量通过修改这个文件来调整参数，而不是命令行参数

# 数据配置
data:
  project_dir: "/home/wangtuo/WorkSpace/lean/LLM-Agent-Lean4-RL/data/benchmarks/lean4"  # 项目目录
  data_dir: "data/benchmarks/lean4/test"

prompt_loader:
  prompts_dir: "data/prompts"
# LLM 配置
llm:
  reasoner:
    model_name: "gpt-5-mini"  # 检索智能体使用的模型
    temperature: 1.0
    max_tokens: 4500
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    max_retries: 3
    retry_delay: 1.0
    base_url: "https://api.chatanywhere.tech"

  verification:
    model: "gpt-4o-mini"  # 验证智能体使用的模型
    temperature: 0.7
    max_tokens: 2048
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    max_retries: 3
    retry_delay: 1.0
    timeout: 60
    base_url: "https://api.chatanywhere.tech"

# Agent 配置
agent:
  retriever:
    index_dir: "data/retriever"
    model_name: "all-mpnet-base-v2"  # 自动使用本地缓存

# 验证器配置
verifier:
  project_path: "/home/wangtuo/WorkSpace/lean/LLM-Agent-Lean4-RL/data/benchmarks/lean4"  # 这个地方给绝对路径
  timeout: 60

# RL 配置（未来）
rl:
  enabled: false
  algorithm: "ppo"
  learning_rate: 0.0001

# 日志配置
logger:
  save_dir: "log"
  log_config: "src/logger/logger_config.json"

